export const AMQP_CONFIG = {
    THIRD_FIRST: {
        QUEUE: 'THIRD_FIRST_QUEUE',
        SERVICE: 'THIRD_FIRST_SERVICE',
    },
    THIRD_SECOND: {
        QUEUE: 'THIRD_SECOND_QUEUE',
        SERVICE: 'THIRD_SECOND_SERVICE',
    },
};

export const AMQP_MESSAGES = {
    SEND_MESSAGE_TO_FIRST: 'SEND_MESSAGE_TO_FIRST',
    SEND_EVENT_TO_FIRST: 'SEND_EVENT_TO_FIRST',
};
