export const AMQP_CONFIG = {
    THIRD_FIRST_1: {
        QUEUE: 'THIRD_FIRST_QUEUE_1',
        SERVICE: 'THIRD_FIRST_SERVICE_1',
    },
    THIRD_FIRST_2: {
        QUEUE: 'THIRD_FIRST_QUEUE_2',
        SERVICE: 'THIRD_FIRST_SERVICE_2',
    },
    THIRD_SECOND: {
        QUEUE: 'THIRD_SECOND_QUEUE',
        SERVICE: 'THIRD_SECOND_SERVICE',
    },
};

export const AMQP_MESSAGES = {
    SEND_MESSAGE_TO_FIRST: 'SEND_MESSAGE_TO_FIRST',
    SEND_EVENT_TO_FIRST: 'SEND_EVENT_TO_FIRST',
};
